version: '3'
services:
  app:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - './config.json:/ai/config/config.json:ro'
      - './font.ttf:/ai/font.ttf:ro'
      - './data:/ai/data'
    restart: always
